name: ShulkerMapCopier
main: me.leingen.shulkermapcopier.ShulkerMapCopierPlugin
version: 1.1.0
api-version: 1.21
folia-supported: true

commands:
  copyShulkerMap:
    description: Copy a shulker box containing filled maps
    usage: /<command> [copies|help]
    aliases: [csm]
    permission: shulkermapcopier.use
    permission-message: "You don't have permission to use this command!"

permissions:
  shulkermapcopier.use:
    description: Allows copying shulker boxes with maps
    default: true