name: Build and Release with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [created]   # Run workflow when a GitHub Release is created

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # Needed for uploading release assets

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Build with Gradle Wrapper
      run: ./gradlew clean build

    # Upload build artifact (for pull requests, debugging, etc.)
    - name: Upload plugin jar as artifact
      uses: actions/upload-artifact@v4
      with:
        name: shulkermapcopier-jar
        path: build/libs/*.jar

    # Attach JAR to GitHub Release (only when triggered by release)
    - name: Upload JAR to GitHub Release
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v2
      with:
        files: build/libs/*.jar
